"""add cuenta_id to transacciones

Revision ID: ef50b3d4f3de
Revises: f31f3a169f3a
Create Date: 2025-07-08 22:32:37.784406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef50b3d4f3de'
down_revision: Union[str, Sequence[str], None] = 'f31f3a169f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
